# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Verilog/test_zynq_11_26/test_zynq_11_26.srcs/sources_1/bd/zynq_basys/ip/zynq_basys_axi_gpio_1_0/zynq_basys_axi_gpio_1_0.xci
# IP: The module: 'zynq_basys_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Verilog/test_zynq_11_26/test_zynq_11_26.gen/sources_1/bd/zynq_basys/ip/zynq_basys_axi_gpio_1_0/zynq_basys_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_basys_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog/test_zynq_11_26/test_zynq_11_26.gen/sources_1/bd/zynq_basys/ip/zynq_basys_axi_gpio_1_0/zynq_basys_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_basys_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog/test_zynq_11_26/test_zynq_11_26.gen/sources_1/bd/zynq_basys/ip/zynq_basys_axi_gpio_1_0/zynq_basys_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_basys_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Verilog/test_zynq_11_26/test_zynq_11_26.srcs/sources_1/bd/zynq_basys/ip/zynq_basys_axi_gpio_1_0/zynq_basys_axi_gpio_1_0.xci
# IP: The module: 'zynq_basys_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Verilog/test_zynq_11_26/test_zynq_11_26.gen/sources_1/bd/zynq_basys/ip/zynq_basys_axi_gpio_1_0/zynq_basys_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_basys_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog/test_zynq_11_26/test_zynq_11_26.gen/sources_1/bd/zynq_basys/ip/zynq_basys_axi_gpio_1_0/zynq_basys_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_basys_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog/test_zynq_11_26/test_zynq_11_26.gen/sources_1/bd/zynq_basys/ip/zynq_basys_axi_gpio_1_0/zynq_basys_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_basys_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
