set_property MARK_DEBUG true [get_nets {cnt[0]}]
set_property MARK_DEBUG true [get_nets {cnt[1]}]
set_property MARK_DEBUG true [get_nets {cnt[2]}]
set_property MARK_DEBUG true [get_nets {cnt[3]}]
set_property MARK_DEBUG true [get_nets {cnt[4]}]
set_property MARK_DEBUG true [get_nets {cnt[5]}]
set_property MARK_DEBUG true [get_nets {cnt[6]}]
set_property MARK_DEBUG true [get_nets {cnt[7]}]
set_property MARK_DEBUG true [get_nets {cnt[8]}]
set_property MARK_DEBUG true [get_nets {cnt[9]}]
set_property MARK_DEBUG true [get_nets {cnt[10]}]
set_property MARK_DEBUG true [get_nets {cnt[11]}]
set_property MARK_DEBUG true [get_nets {cnt[12]}]
set_property MARK_DEBUG true [get_nets {cnt[13]}]
set_property MARK_DEBUG true [get_nets {cnt[14]}]
set_property MARK_DEBUG true [get_nets {cnt[15]}]
set_property MARK_DEBUG true [get_nets {cnt[16]}]
set_property MARK_DEBUG true [get_nets {cnt[17]}]
set_property MARK_DEBUG true [get_nets {cnt[18]}]
set_property MARK_DEBUG true [get_nets {cnt[19]}]
set_property MARK_DEBUG true [get_nets {cnt[20]}]
set_property MARK_DEBUG true [get_nets {cnt[21]}]
set_property MARK_DEBUG true [get_nets {cnt[22]}]
set_property MARK_DEBUG true [get_nets {cnt[23]}]
set_property MARK_DEBUG true [get_nets {cnt[24]}]
set_property MARK_DEBUG true [get_nets {cnt[25]}]
set_property MARK_DEBUG true [get_nets {cnt[26]}]
set_property MARK_DEBUG true [get_nets {cnt[27]}]
set_property MARK_DEBUG true [get_nets {cnt[28]}]
set_property MARK_DEBUG true [get_nets {cnt[29]}]
set_property MARK_DEBUG true [get_nets {cnt[30]}]
set_property MARK_DEBUG true [get_nets {cnt[31]}]
set_property MARK_DEBUG true [get_nets rst_IBUF]

set_property MARK_DEBUG true [get_nets enable]
set_property MARK_DEBUG true [get_nets RST_IBUF]
set_property MARK_DEBUG true [get_nets {LED_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {LED_OBUF[1]}]
set_property MARK_DEBUG true [get_nets {LED_OBUF[2]}]
set_property MARK_DEBUG true [get_nets {LED_OBUF[3]}]
set_property MARK_DEBUG true [get_nets {LED_OBUF[4]}]
set_property MARK_DEBUG true [get_nets {LED_OBUF[5]}]
set_property MARK_DEBUG true [get_nets {LED_OBUF[6]}]
set_property MARK_DEBUG true [get_nets {LED_OBUF[7]}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list CLK_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {LED_OBUF[0]} {LED_OBUF[1]} {LED_OBUF[2]} {LED_OBUF[3]} {LED_OBUF[4]} {LED_OBUF[5]} {LED_OBUF[6]} {LED_OBUF[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 27 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {cnt[0]} {cnt[1]} {cnt[2]} {cnt[3]} {cnt[4]} {cnt[5]} {cnt[6]} {cnt[7]} {cnt[8]} {cnt[9]} {cnt[10]} {cnt[11]} {cnt[12]} {cnt[13]} {cnt[14]} {cnt[15]} {cnt[16]} {cnt[17]} {cnt[18]} {cnt[19]} {cnt[20]} {cnt[21]} {cnt[22]} {cnt[23]} {cnt[24]} {cnt[25]} {cnt[26]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list enable]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list RST_IBUF]]
set_property PACKAGE_PIN W14 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN Y14 [get_ports {LED[6]}]
set_property PACKAGE_PIN T11 [get_ports {LED[5]}]
set_property PACKAGE_PIN T10 [get_ports {LED[4]}]
set_property PACKAGE_PIN V16 [get_ports {LED[3]}]
set_property PACKAGE_PIN W16 [get_ports {LED[2]}]
set_property PACKAGE_PIN V12 [get_ports {LED[1]}]
set_property PACKAGE_PIN W13 [get_ports {LED[0]}]
set_property PACKAGE_PIN H16 [get_ports CLK]
set_property PACKAGE_PIN D19 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets CLK_IBUF_BUFG]
