

set_property MARK_DEBUG true [get_nets start_stop_IBUF]
set_property MARK_DEBUG true [get_nets {sec1[0]}]
set_property MARK_DEBUG true [get_nets {sec1[1]}]
set_property MARK_DEBUG true [get_nets {sec1[2]}]
set_property MARK_DEBUG true [get_nets {sec1[3]}]
set_property MARK_DEBUG true [get_nets {sec1[4]}]
set_property MARK_DEBUG true [get_nets {sec1[5]}]
set_property MARK_DEBUG true [get_nets {sec2[0]}]
set_property MARK_DEBUG true [get_nets {sec2[1]}]
set_property MARK_DEBUG true [get_nets {sec2[2]}]
set_property MARK_DEBUG true [get_nets {sec2[3]}]
set_property MARK_DEBUG true [get_nets {sec2[4]}]
set_property MARK_DEBUG true [get_nets {sec2[5]}]
set_property MARK_DEBUG true [get_nets clear_lap_IBUF]
set_property MARK_DEBUG true [get_nets SAVE]
connect_debug_port u_ila_0/probe2 [get_nets [list clear_lap_IBUF]]


set_property MARK_DEBUG true [get_nets {state[0]}]
set_property MARK_DEBUG true [get_nets {state[1]}]

set_property MARK_DEBUG true [get_nets {SAVE_reg_n_0_[3][0]}]
set_property MARK_DEBUG true [get_nets {SAVE_reg_n_0_[3][5]}]
set_property MARK_DEBUG true [get_nets {SAVE_reg_n_0_[3][2]}]
set_property MARK_DEBUG true [get_nets {SAVE_reg_n_0_[3][1]}]
set_property MARK_DEBUG true [get_nets {SAVE_reg_n_0_[3][3]}]
set_property MARK_DEBUG true [get_nets {SAVE_reg_n_0_[3][4]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 6 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {sec1[0]} {sec1[1]} {sec1[2]} {sec1[3]} {sec1[4]} {sec1[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 3 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {state[0]} {state[1]} {state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 6 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {sec2[0]} {sec2[1]} {sec2[2]} {sec2[3]} {sec2[4]} {sec2[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list clear_lap_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list SAVE]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {SAVE_reg_n_0_[3][0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {SAVE_reg_n_0_[3][1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {SAVE_reg_n_0_[3][2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {SAVE_reg_n_0_[3][3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {SAVE_reg_n_0_[3][4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {SAVE_reg_n_0_[3][5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list start_stop_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
