domain_path: C:\Verilog\Zynq_AXI_7Segment_Vitis2\Zynq_AXI_7Segment_Vistis\export\Zynq_AXI_7Segment_Vistis\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
